import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { buildFixtures, type FixtureFile } from '@auralis/core';

/**
 * Fixture materialisation.
 *
 * The fixture *content* is generated by `@auralis/core`, so the same bytes are
 * used by unit tests, integration tests and the bundled origin server. This
 * module only puts them on disk for the local-files provider and for manual
 * inspection.
 */

export { buildFixtures };
export type { FixtureFile };

/** Writes the fixture set to disk. Idempotent. */
export function writeFixtures(directory: string): readonly FixtureFile[] {
  mkdirSync(directory, { recursive: true });
  const fixtures = buildFixtures();
  for (const fixture of fixtures) {
    writeFileSync(join(directory, fixture.name), fixture.bytes);
  }
  return fixtures;
}
